"""empty message

Revision ID: 16885484f1dc
Revises: 6559a7805c68
Create Date: 2023-10-02 01:24:08.526599

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '16885484f1dc'
down_revision = '6559a7805c68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_reset', sa.Unicode(length=255), nullable=True))
    op.add_column('user', sa.Column('balance', sa.Integer(), nullable=False))
    op.drop_column('user', 'password_reset_encrypted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_reset_encrypted', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('user', 'balance')
    op.drop_column('user', 'password_reset')
    # ### end Alembic commands ###
