"""empty message

Revision ID: 6559a7805c68
Revises: 7eca65df8aa0
Create Date: 2023-10-01 23:52:18.875529

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6559a7805c68'
down_revision = '7eca65df8aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_post',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('title', sa.Unicode(length=255), nullable=False),
    sa.Column('recruitment_object', sa.Unicode(length=255), nullable=True),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('benefit', sa.TEXT(), nullable=True),
    sa.Column('other_information', sa.TEXT(), nullable=True),
    sa.Column('bonus', sa.Integer(), nullable=True),
    sa.Column('currency', sa.Unicode(length=255), nullable=False),
    sa.Column('type', sa.Unicode(length=255), nullable=False),
    sa.Column('status', sa.Unicode(length=32), nullable=False),
    sa.Column('expired_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('password', sa.Unicode(length=255), nullable=False))
    op.add_column('user', sa.Column('code', sa.Unicode(length=255), nullable=False))
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.alter_column('user', 'fullname',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.drop_index('username', table_name='user')
    op.create_unique_constraint(None, 'user', ['code'])
    op.create_unique_constraint(None, 'user', ['email'])
    op.create_unique_constraint(None, 'user', ['phone'])
    op.drop_column('user', 'username')
    op.drop_column('user', 'password_encrypted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_encrypted', mysql.VARCHAR(length=255), nullable=True))
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('username', 'user', ['username'], unique=False)
    op.alter_column('user', 'fullname',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'phone',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_column('user', 'code')
    op.drop_column('user', 'password')
    op.drop_table('job_post')
    # ### end Alembic commands ###
